### ISSUE TITLE
Doesn't work on Visual Studio 2015 Professional

### ISSUE THREAD

**Issue by Powlinz** [aldobrynin/CleanBinAndObj#2]
I doesn't work using Visual Studio 2015 Pro
I get an error VSIXInstaller.NoApplicableSKUsException 

Is it because my VS is in french ?

**Comment by aldobrynin** [comment]
I don't think it's locale related issue, maybe extension isn't compatible with VS2015. I'll investigate this problem a bit later.
Could you please attach installation log file?

**Comment by Powlinz** [comment]
[VSIXInstaller_4b12b75e-9721-4dab-b265-e7a3864255d2.log](https://github.com/aldobrynin/CleanBinAndObj/files/2586158/VSIXInstaller_4b12b75e-9721-4dab-b265-e7a3864255d2.log)

Yup, It look like it don't work in VS 2015 I tried others extensions that give the same error but they only support 2017, this one is supposed to work with Visual Studio 2010, 2012, 2013, 2015, 2017 so I think it was a bug or something

Thanks

**Comment by aldobrynin** [comment]
@Powlinz I've updated package's target VS versions and it should work with VS2015 as well.
Have a try

**Comment by Powlinz** [comment]
Yeah It work now 
thank you!
