### ISSUE TITLE
Command name

### ISSUE THREAD

**Issue by RealHabix** [aldobrynin/CleanBinAndObj#3]
Is it possible to expose this extension with a "command name" (so we can bind a keyboard hotkey to this extension)?

**Comment by aldobrynin** [comment]
yea, for sure
give it a try with [version 1.1.28](https://marketplace.visualstudio.com/items?itemName=dobrynin.cleanbinandobj)

**Comment by GvmiHasan** [comment]
@aldobrynin also, if you can add an icon for it. that's help to showing in image style on toolbar.
thanks 🧡

**Comment by RealHabix** [comment]
> yea, for sure
> give it a try with [version 1.1.28](https://marketplace.visualstudio.com/items?itemName=dobrynin.cleanbinandobj)

Perfect - I owe you a beer!

**Comment by aldobrynin** [comment]
@RealHabix you're welcome
@GvmiHasan please open an issue for that. I'll check what I can do later, or you can try implementing it yourself. I'll be glad to see PR from you :)
Closing this issue now
