### ISSUE TITLE
Any plan to support VS 2022

### ISSUE THREAD

**Issue by rizi** [aldobrynin/CleanBinAndObj#9]
Hi,
VS 2022 will be released on November 8 (2021), any plan to support it?

br

**Comment by janis3000** [comment]
https://github.com/janis3000/CleanBinAndObj/tree/vs2022_support

**Comment by aldobrynin** [comment]
I'll try to publish it, but PRs are welcome and will help to do it faster since I don't have VS installed atm

**Comment by janis3000** [comment]
Yes sorry, did not have much time on that. I also have to admit I didn't test backwards compatibility to older VS versions.

**Comment by rizi** [comment]
> Yes sorry, did not have much time on that. I also have to admit I didn't test backwards compatibility to older VS versions.

@janis3000 thx for your work, with VS 2022 it's absolutely running fine !

There are some warnings, that we should check if we are on the main/ui thread, but I don't have ever written a VS plugin, so I don't know if the check is really necessary in this cases.

Br

**Comment by aldobrynin** [comment]
just published release with vs2022 support, enjoy
